### ISSUE TITLE
Use alternative names for beacon/execution nodes

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/eth-network-package#46]
I would like to propose a change for `cl-client-0-beacon` name to become `teku-geth-0` and `el-client-0` to be called `geth-teku-0`. 
Its quite hard to keep track of which pair is what, when you run a lot of client mixes
Basically I would like to have <el>-<cl> for the EL node, and <cl>-<el> for the CL node

https://github.com/kurtosis-tech/eth-network-package/blob/07d81fa0b5e5a2d71598da15033c07f1a07068b7/src/participant_network.star#L156

**Comment by leeederek** [comment]
Hey @barnabasbusa, I've opened: #47 to address this. I am keeping the `-beacon` and `-validator` suffix but otherwise have implemented the change you propose, mapping `cl-client-0-beacon` to `lighthouse-geth-0-beacon` for the case where the CL client is lighthouse and the EL client is geth. 

Let me know what you think!

**Comment by leeederek** [comment]
@barnabasbusa thinking about it a bit further, is there a reason you want *both* the CL and EL names? Would an output (below) be sufficient for your needs?
```python
lighthouse-beacon-0
lighthouse-validator-0
geth-0
```

The reason I ask is because as a user who may not be familiar with the various client implementations, I may get confused if I see the names of 2 clients together like so:
```python
lighthouse-geth-beacon-0
lighthouse-geth-validator-0
geth-lighthouse-0
```
Which would throw me off (i.e. how would they know which one is the EL if they didn't know `geth` was a EL client?)

**Comment by barnabasbusa** [comment]
If you got 10-15 different pairs with different client combos it would be very good to easily find which exact pair is running with which pair. This is why I would prefer to have EL and CL both in the name.

**Comment by leeederek** [comment]
Got it, makes sense :) #47 should give you what you need then!

**Comment by barnabasbusa** [comment]
I'd argue, that its not needed to have beacon in the name, as its implicit. 
So I would like to have
``` 
lighthouse-geth-0
lighthouse-geth-validator-0
geth-lighthouse-0
```
and for CLs that have validators within the beacon process, just leave out the validator altogether.
```
teku-geth-0
```

**Comment by barnabasbusa** [comment]
Would it be possible that instead of unique indexing for each pair, we would use a unique per pair? e.g lighthouse-geth-0 and lodestar-geth-0 instead of lighthouse-geth-0 lodestar-geth-1 ? 
It would also be great if we could have a new participant field where we could have a new variable called count, where we could define we need 5 ligthhouse-geth pairs for example, and it would spin that up, without needing to define it 5 times the same thing.

**Comment by leeederek** [comment]
Gotcha, which CLs have validators within the beacon process? 
> and for CLs that have validators within the beacon process, just leave out the validator altogether.

**Comment by leeederek** [comment]
Hello @barnabasbusa, after some review, I propose the following service name format for a set up where you have 2 nodes, one that is a geth/lighthouse pair and another that is a geth/teku pair:
```bash
0-cl-client-lighthouse
0-cl-client-lighthouse-validator
0-el-client-geth
1-cl-client-teku
1-el-client-geth
```

Reasons:
- The number at the beginning is indexed based on the pair and is used to differentiate the pairs of clients per node. Also since `kurtosis enclave inspect` lists service names alphabetically by default, you will always see the nodes grouped together regardless of the client pair combination
- I've removed the `beacon` suffix and left the validator suffix only for validators that do not have validators within the beacon process.

Does that work for you? I believe this is an improvement to the status quo while still letting a user understand which node has what type of client pair.

**Comment by barnabasbusa** [comment]
I would personally prefer if cl-client and el-client gets dropped.
Personally I think if someone is running kurtosis, that they are aware that there is an el and a cl, and they are aware that which client is what. If they don't know what el-client or cl-client means, then having it in the name will not help them anyways.
Hence, having that there is in my opinion redundant. 

Also not having the matching pair within the same name is nice and easy at first, but trust me as soon as you have 25 different possible combinations, its going to be a lot more difficult to keep in mind, hence why I suggested to use the EL-CL name for EL nodes, and CL-EL name for CL nodes.
